# Generated by Django 4.0.6 on 2022-12-19 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import users.managers
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(blank=True, default=None, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(blank=True, default=None, max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=60)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer not to say', 'Prefer not to say')], max_length=50)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('age', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardians_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fathers_mail', models.EmailField(blank=True, max_length=60, null=True)),
                ('mothers_mail', models.EmailField(blank=True, max_length=60, null=True)),
                ('guardians_mail', models.EmailField(blank=True, max_length=60, null=True)),
                ('fathers_phone_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('fathers_phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('mothers_phone_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('mothers_phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('guardians_phone_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('guardians_phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('class_name', models.CharField(choices=[('primary_school', 'Primary School'), ('preschool_one', 'Preschool 1'), ('preschool_two', 'Preschool 2'), ('nursery_one', 'Nursery 1'), ('nursery_two', 'Nursery 2'), ('grade_one', 'Grade 1'), ('grade_two', 'Grade 2'), ('grade_three', 'Grade 3'), ('grade_four', 'Grade 4'), ('grade_five', 'Grade 5')], max_length=50)),
                ('profile_image', models.ImageField(blank=True, default=users.models.get_default_profile_image, max_length=255, upload_to=users.models.get_profile_image_filepath)),
                ('reg_year', models.IntegerField(default=2022, verbose_name='registration year')),
                ('reg_date', models.DateField(default=django.utils.timezone.now, verbose_name='registration date')),
                ('reg_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='registration number')),
                ('is_idd', models.BooleanField(default=False, editable=False)),
                ('related_to', models.ManyToManyField(blank=True, default=None, related_name='related_students', to=settings.AUTH_USER_MODEL)),
                ('user_obj', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(blank=True, default=None, max_length=50)),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer not to say', 'Prefer not to say')], max_length=50)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('age', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=50)),
                ('spouse_name', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('spouse_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('post', models.CharField(choices=[('head_teacher', 'Head Teacher'), ('hod_nursery', 'HOD Nursery'), ('hod_primary', 'HOD Primary'), ('class_teacher', 'Class Teacher'), ('janitor', 'Janitor'), ('driver', 'Driver')], default=None, max_length=50)),
                ('class_name', models.CharField(choices=[('primary_school', 'Primary School'), ('preschool_one', 'Preschool 1'), ('preschool_two', 'Preschool 2'), ('nursery_one', 'Nursery 1'), ('nursery_two', 'Nursery 2'), ('grade_one', 'Grade 1'), ('grade_two', 'Grade 2'), ('grade_three', 'Grade 3'), ('grade_four', 'Grade 4'), ('grade_five', 'Grade 5')], default=None, max_length=50)),
                ('profile_image', models.ImageField(blank=True, default=users.models.get_default_profile_image, max_length=255, upload_to=users.models.get_profile_image_filepath)),
                ('emp_year', models.IntegerField(default=2022, verbose_name='employment year')),
                ('emp_date', models.DateField(default=django.utils.timezone.now, verbose_name='employment date')),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='staff_id')),
                ('is_idd', models.BooleanField(default=False, editable=False)),
                ('related_to', models.ManyToManyField(blank=True, default=None, related_name='related_staffs', to=settings.AUTH_USER_MODEL)),
                ('user_obj', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
