# Generated by Django 4.0.6 on 2022-12-19 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('brief', models.TextField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(help_text='Image size should be 960x400, also this image will be used as thumbnail', null=True, upload_to='events_images', verbose_name='Main Image')),
                ('sub_image1', models.ImageField(blank=True, null=True, upload_to='events_images', verbose_name='Sub Image 1')),
                ('sub_image1_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Sub Image 1 Description')),
                ('sub_image2', models.ImageField(blank=True, null=True, upload_to='events_images', verbose_name='Sub Image 2')),
                ('sub_image2_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Sub Image 2 Description')),
                ('sub_image3', models.ImageField(blank=True, null=True, upload_to='events_images', verbose_name='Sub Image 3')),
                ('sub_image3_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Sub Image 3 Description')),
                ('sub_image4', models.ImageField(blank=True, null=True, upload_to='events_images', verbose_name='Sub Image 4')),
                ('sub_image4_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Sub Image 4 Description')),
                ('video_link', models.URLField(blank=True, help_text='Paste the link of the video here', null=True, verbose_name='Video Link')),
                ('video_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Video Description')),
                ('views', models.IntegerField(default=0, editable=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
