# Generated by Django 4.1 on 2022-12-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_event_date_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='added_by',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=200),
        ),
    ]
