# Generated by Django 4.1 on 2022-12-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['question']},
        ),
    ]
