# Generated by Django 4.1 on 2023-01-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_job_is_open_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=100),
        ),
    ]
